"""munim contribute — turn your confirmed labels into a PR-ready,
anonymized contribution bundle. This operationalizes Loop 4: every merchant
you label can improve cold-start accuracy for everyone.

Privacy rules enforced IN CODE, not just in docs:
  - merchant patterns only — payee (person) rules are never exported
  - no amounts, no dates, no account names, no raw descriptions
  - the user reviews the generated file before opening a PR
"""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import yaml

from .memory import MemoryMatcher
from .store import Store

GENERIC_TOKENS = {"PAYMENT", "ONLINE", "TRANSFER", "RECHARGE", "CHARGE"}


def collect_candidates(store: Store) -> tuple[dict[str, list[str]], int]:
    """Merchant patterns worth contributing: confirmed by the user, not yet
    in the community dictionary, safe to share. Payee rules never leave."""
    region = store.get_config("region", "in")
    user_rules = store.memory_rules("merchant")
    matcher = MemoryMatcher(user_rules={}, region=region)
    candidates: dict[str, list[str]] = defaultdict(list)
    skipped = 0
    for pattern, category in sorted(user_rules.items()):
        if matcher.match(pattern):
            skipped += 1
            continue
        if len(pattern) < 4 or pattern in GENERIC_TOKENS:
            skipped += 1
            continue
        candidates[category].append(pattern)
    return candidates, skipped


def build_bundle(store: Store, out_dir: Path) -> dict:
    region = store.get_config("region", "in")
    candidates, skipped = collect_candidates(store)

    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"dictionary_candidates_{region}.yaml"
    header = (
        "# Munim community dictionary candidates\n"
        f"# Region: {region}\n"
        "# Generated by `munim contribute` from user-confirmed labels.\n"
        "# REVIEW BEFORE SUBMITTING:\n"
        "#  - remove anything local-only (your society's grocer helps nobody)\n"
        "#  - remove anything that could identify you\n"
        "# Then append entries to munim/data/dictionary/"
        f"{region}.yaml and open a PR.\n\n"
    )
    out_file.write_text(header + yaml.safe_dump(
        {k: sorted(v) for k, v in candidates.items()},
        allow_unicode=True, sort_keys=True))
    return {
        "file": str(out_file),
        "patterns": sum(len(v) for v in candidates.values()),
        "categories": len(candidates),
        "skipped_known_or_unsafe": skipped,
    }
